# vim:ft=kitty

## name: GitHub Light
## author: projekt0n (https://github.com/projekt0n)
## license: MIT
## upstream: https://github.com/projekt0n/github-nvim-theme
## blurb: GitHub's light color scheme for kitty


#: The basic colors

foreground #1f2328
background #ffffff
selection_foreground #1f2328
selection_background #add6ff


#: Cursor colors

cursor #0969da
cursor_text_color #ffffff


#: URL underline color when hovering with mouse

url_color #0969da


#: kitty window border colors and terminal bell colors

active_border_color #d0d7de
inactive_border_color #ffffff
bell_border_color #9a6700
visual_bell_color none


#: OS Window titlebar colors

wayland_titlebar_color #f6f8fa
macos_titlebar_color #f6f8fa


#: Tab bar colors

active_tab_foreground #1f2328
active_tab_background #ffffff
inactive_tab_foreground #57606a
inactive_tab_background #f6f8fa
tab_bar_background #f6f8fa
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)

mark1_foreground #ffffff
mark1_background #0969da
mark2_foreground #ffffff
mark2_background #1a7f37
mark3_foreground #ffffff
mark3_background #9a6700


#: The basic 16 colors

#: black
color0 #24292f
color8 #57606a

#: red
color1 #cf222e
color9 #a40e26

#: green
color2 #1a7f37
color10 #2da44e

#: yellow
color3 #9a6700
color11 #bf8700

#: blue
color4 #0969da
color12 #218bff

#: magenta
color5 #8250df
color13 #a475f9

#: cyan
color6 #1b7c83
color14 #3192aa

#: white
color7 #6e7781
color15 #8c959f
